#Local docker-compose
version: '3.9'

services:
  spring-brandbank-api:
      build:
        context: ../
        dockerfile: ./docker/Dockerfile
      ports:
        - "8080:8080"
      environment:
        SPRING_PROFILE: dev